// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWUXd4XyM4cLZ4syqrD9J8VihMQisJi0I',
    appId: '1:331512369770:web:bd914b441e533efa463013',
    messagingSenderId: '331512369770',
    projectId: 'pushnotificationupdate1',
    authDomain: 'pushnotificationupdate1.firebaseapp.com',
    storageBucket: 'pushnotificationupdate1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFWpI4oAV955v4l4CYlr2va5GlRZpNRhA',
    appId: '1:331512369770:android:48fc2c301414a4e8463013',
    messagingSenderId: '331512369770',
    projectId: 'pushnotificationupdate1',
    storageBucket: 'pushnotificationupdate1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmsm_YkaVZN2oqKk-q-htT6gdPnAm6b2k',
    appId: '1:331512369770:ios:5e4605ce1e599252463013',
    messagingSenderId: '331512369770',
    projectId: 'pushnotificationupdate1',
    storageBucket: 'pushnotificationupdate1.appspot.com',
    iosBundleId: 'com.example.pushnotificationupdate1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmsm_YkaVZN2oqKk-q-htT6gdPnAm6b2k',
    appId: '1:331512369770:ios:5e4605ce1e599252463013',
    messagingSenderId: '331512369770',
    projectId: 'pushnotificationupdate1',
    storageBucket: 'pushnotificationupdate1.appspot.com',
    iosBundleId: 'com.example.pushnotificationupdate1',
  );
}
